#!/bin/bash

Mod=Mod1

herbstclient emit_hook reload
xsetroot -solid "#010101"

herbstclient keyunbind --all

herbstclient keybind $Mod-Shift-q quit
herbstclient keybind $Mod-Shift-r reload
herbstclient keybind $Mod-Shift-c close
herbstclient keybind $Mod-Return spawn urxvtc
herbstclient keybind $Mod-p spawn dmenu_run -fn -xos4-terminus-medium-r-normal--12-120-72-72-c-60-iso8859-15 -nb rgb:01/01/01 -nf rgb:240/240/240 -sb rgb:240/240/240 -sf rgb:01/01/01

# Tags
TAG_NAMES=(multimedia web im dev1 dev2 dev3 dev4 dev5 dev6 dev7)
herbstclient rename default "${TAG_NAMES[0]}" || true
for i in ${!TAG_NAMES[@]}; do
	herbstclient add "${TAG_NAMES[$i]}"
	herbstclient keybind "$Mod-$i" use "${TAG_NAMES[$i]}"
	herbstclient keybind "$Mod-Shift-$i" move "${TAG_NAMES[$i]}"
done

# Layout
herbstclient keybind $Mod-r remove
herbstclient keybind $Mod-space cycle_layout 1
herbstclient keybind $Mod-u split vertical 0.5
herbstclient keybind $Mod-o split horizontal 0.5
#herbstclient keybind $Mod-s floating toggle
herbstclient keybind $Mod-f fullscreen toogle
#herbstclient keybind $Mod-p pseudotile toggle

# Resizing
RSZSTEP=0.05
herbstclient keybind $Mod-Control-h resize left +$RSZSTEP
herbstclient keybind $Mod-Control-l resize right +$RSZSTEP
herbstclient keybind $Mod-Control-j resize down +$RSZSTEP
herbstclient keybind $Mod-Control-k resize up +$RSZSTEP

# Focus
herbstclient keybind $Mod-Tab cycle_all +1
herbstclient keybind $Mod-Shift-Tab cycle_all -1
herbstclient keybind $Mod-c cycle
herbstclient keybind $Mod-h focus left
herbstclient keybind $Mod-l focus right
herbstclient keybind $Mod-j focus down
herbstclient keybind $Mod-k focus up
herbstclient keybind $Mod-Shift-h shift left
herbstclient keybind $Mod-Shift-l shift right
herbstclient keybind $Mod-Shift-j shift down
herbstclient keybind $Mod-Shift-k shift up

# Colors
herbstclient set frame_border_active_color "#fff"
herbstclient set frame_border_normal_color "#010101"
herbstclient set frame_bg_active_color "#010101"
herbstclient set frame_bg_normal_color "#010101"
herbstclient set frame_bg_transparent 1
herbstclient set frame_border_width 1
herbstclient set window_border_width 0
herbstclient set window_border_normal_color "#010101"
herbstclient set window_border_active_color "#ff0000"
